[build-system]
requires = [
    "build",
    "setuptools",
    "wheel",
    "chardet",
    "jupyter",
    "jupyterhub",
#    "git+https://github.com/coleifer/pysqlite3.git",
    "notebook",
    "numpy",
    "pandas",
    "regex",
    "unidecode"
]
build-backend = "setuptools.build_meta"
